server {
    error_log /var/log/nginx/gramm_error.log;
    access_log /var/log/nginx/gramm_access.log;

    listen 80;

    root /build;

    index /index.html;
    
    location /api/ {
        proxy_pass http://localhost:8080/api/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}